// VK_EXT_extended_dynamic_state functions used in Xenia.
// Promoted to Vulkan 1.3 core.
XE_UI_VULKAN_FUNCTION_PROMOTED(vkCmdSetCullModeEXT, vkCmdSetCullMode)
XE_UI_VULKAN_FUNCTION_PROMOTED(vkCmdSetFrontFaceEXT, vkCmdSetFrontFace)
XE_UI_VULKAN_FUNCTION_PROMOTED(vkCmdSetDepthTestEnableEXT, vkCmdSetDepthTestEnable)
XE_UI_VULKAN_FUNCTION_PROMOTED(vkCmdSetDepthWriteEnableEXT,
                               vkCmdSetDepthWriteEnable)
XE_UI_VULKAN_FUNCTION_PROMOTED(vkCmdSetDepthCompareOpEXT, vkCmdSetDepthCompareOp)
