#!/usr/bin/env python3
"""Per-title development ledger (SQLite) with a Markdown export.

One row per title (status, fps, last build, blockers) and one event row per
finding, fix, or measurement. The Markdown export docs/games/STATUS.md is
committed with the database so the state is readable without the tool.

  python tools/game_ledger.py set <title_id> <name> <status> [fps] [build] [notes]
  python tools/game_ledger.py event <title_id> <kind> "<text>" [commit]
  python tools/game_ledger.py show <title_id>
  python tools/game_ledger.py list
  python tools/game_ledger.py export          # writes docs/games/STATUS.md

status: BOOTS, TITLE, GAMEPLAY, STALL, CRASH, UNTESTED
kind:   finding, fix, measurement, blocker, patch, note
"""
import datetime
import os
import sqlite3
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB = os.path.join(ROOT, "docs", "research", "games.db")
MD = os.path.join(ROOT, "docs", "games", "STATUS.md")


def db():
    os.makedirs(os.path.dirname(DB), exist_ok=True)
    c = sqlite3.connect(DB)
    c.execute("""CREATE TABLE IF NOT EXISTS titles (
        title_id TEXT PRIMARY KEY, name TEXT, status TEXT, fps TEXT, build TEXT,
        notes TEXT, updated TEXT)""")
    c.execute("""CREATE TABLE IF NOT EXISTS events (
        id INTEGER PRIMARY KEY, title_id TEXT, date TEXT, kind TEXT, text TEXT,
        commit_hash TEXT)""")
    return c


def today():
    return datetime.date.today().isoformat()


def cmd_set(args):
    title_id, name, status = args[0].upper(), args[1], args[2].upper()
    fps = args[3] if len(args) > 3 else ""
    build = args[4] if len(args) > 4 else ""
    notes = args[5] if len(args) > 5 else ""
    c = db()
    c.execute("""INSERT INTO titles(title_id,name,status,fps,build,notes,updated)
                 VALUES(?,?,?,?,?,?,?)
                 ON CONFLICT(title_id) DO UPDATE SET name=excluded.name,
                 status=excluded.status, fps=excluded.fps, build=excluded.build,
                 notes=excluded.notes, updated=excluded.updated""",
              (title_id, name, status, fps, build, notes, today()))
    c.commit()
    print(f"[{status}] {title_id} {name}")


def cmd_event(args):
    title_id, kind, text = args[0].upper(), args[1], args[2]
    commit = args[3] if len(args) > 3 else ""
    c = db()
    c.execute("INSERT INTO events(title_id,date,kind,text,commit_hash) VALUES(?,?,?,?,?)",
              (title_id, today(), kind, text, commit))
    c.commit()
    print(f"{title_id} {kind}: {text[:80]}")


def cmd_show(args):
    c = db()
    row = c.execute("SELECT * FROM titles WHERE title_id=?", (args[0].upper(),)).fetchone()
    print(row)
    for e in c.execute("SELECT date,kind,text,commit_hash FROM events WHERE title_id=? ORDER BY id",
                       (args[0].upper(),)):
        print("  ", e)


def cmd_list(args):
    c = db()
    for r in c.execute("SELECT title_id,name,status,fps,build,updated FROM titles ORDER BY name"):
        print(r)


def cmd_export(args):
    c = db()
    lines = ["# Title status", "",
             "Generated by `tools/game_ledger.py export` from `docs/research/games.db`. "
             "Do not edit by hand.", "",
             "| title | id | status | fps | build | updated | notes |", "|---|---|---|---|---|---|---|"]
    for r in c.execute("SELECT name,title_id,status,fps,build,updated,notes FROM titles ORDER BY name"):
        lines.append("| " + " | ".join(str(x or "") for x in r) + " |")
    for r in c.execute("SELECT title_id,name FROM titles ORDER BY name"):
        lines += ["", f"## {r[1]} ({r[0]})", ""]
        for e in c.execute("SELECT date,kind,text,commit_hash FROM events WHERE title_id=? ORDER BY id", (r[0],)):
            tail = f" (`{e[3]}`)" if e[3] else ""
            lines.append(f"- {e[0]} {e[1]}: {e[2]}{tail}")
    os.makedirs(os.path.dirname(MD), exist_ok=True)
    with open(MD, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", MD)


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 1
    cmd = sys.argv[1]
    fn = {"set": cmd_set, "event": cmd_event, "show": cmd_show, "list": cmd_list,
          "export": cmd_export}.get(cmd)
    if not fn:
        print(__doc__)
        return 1
    fn(sys.argv[2:])
    return 0


if __name__ == "__main__":
    sys.exit(main())
